spring:
  datasource:
    username: myDB
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '1234'
  thymeleaf:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  jpa:
    database: mysql   # ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ?? ?? ??

    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework: info
    com:
      portfolio:
        blog: debug
server:
  port: '9090'

  spring:
    devtools:
      livereload:
        enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false

  server:
    servlet:
      session:
        timeout: -1


postImgLocation : /Users/Kungas_57/Desktop/study_java/test/src/main/resources/static/assets/upload
uploadPath : file:///Users/Kungas_57/Desktop/study_java/test/
